### ISSUE TITLE
AutoSplit 2.0 alpha 5 crashes after changing Capture Method to my capture card

### ISSUE THREAD

**Issue by RyMacG5** [Avasam/Auto-Split#47]
After creating a settings file with my capture card as the capture method on Alpha 5, I receive this error message on startup.

"Traceback (most recent call last):

  File "AutoSplit.py", line 914, in main

  File "AutoSplit.py", line 211, in __init__

  File "user_profile.py", line 189, in load_settings_on_open

  File "user_profile.py", line 165, in load_settings

  File "user_profile.py", line 150, in __load_settings_from_file

  File "capture_method\VideoCaptureDeviceCaptureMethod.py", line 80, in recover_window

NotImplementedError"

Curiously, this does not happen on Alpha 4. Everything works normally.

My capture device is the EVGA XR1 Lite, if that matters.

**Comment by Avasam** [comment]
Thank you for the report. I suggest staying on alpha-4 for now. We're basing the official 2.0 release from it as we did notice a few issues in alpha-5.

**Comment by Avasam** [comment]
@RyMacG5 Please try https://github.com/Avasam/Auto-Split/releases/tag/v2.0.0-alpha.6
