### ISSUE TITLE
[Linux] No module named 'win32'

### ISSUE THREAD

**Issue by Gamebuster19901** [Avasam/Auto-Split#62]
Error:

```
Traceback (most recent call last):
  File "/home/gamebuster/Desktop/autosplit/AutoSplit/scripts/../src/AutoSplit.py", line 20, in <module>
    import error_messages
  File "/home/gamebuster/Desktop/autosplit/AutoSplit/src/error_messages.py", line 13, in <module>
    from utils import FROZEN, GITHUB_REPOSITORY
  File "/home/gamebuster/Desktop/autosplit/AutoSplit/src/utils.py", line 14, in <module>
    from win32 import win32gui
ModuleNotFoundError: No module named 'win32'
```

I recently updated from a 2.0.0 alpha version to 2.0.0.

I ran `./scripts/install.ps1`, and all requirements are satisifed. (output below)

```
PS /home/gamebuster/Desktop/autosplit/AutoSplit> ./scripts/install.ps1
Requirement already satisfied: wheel in /usr/local/lib/python3.10/dist-packages (0.40.0)
Requirement already satisfied: pip in /usr/local/lib/python3.10/dist-packages (23.1.1)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (67.7.2)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Collecting keyboard (from -r /home/gamebuster/Desktop/autosplit/AutoSplit/scripts/requirements.txt (line 15))
  Cloning https://github.com/boppreh/keyboard.git to /tmp/pip-install-93xoz959/keyboard_e272845e98e44d40ae0f80ef3932162c
  Running command git clone --filter=blob:none --quiet https://github.com/boppreh/keyboard.git /tmp/pip-install-93xoz959/keyboard_e272845e98e44d40ae0f80ef3932162c
  Resolved https://github.com/boppreh/keyboard.git to commit d232de09bda50ecb5211ebcc59b85bc6da6aaa24
  Preparing metadata (setup.py) ... done
Ignoring pygrabber: markers 'sys_platform == "win32"' don't match your environment
Ignoring pywin32: markers 'sys_platform == "win32"' don't match your environment
Ignoring winsdk: markers 'sys_platform == "win32"' don't match your environment
Ignoring D3DShot: markers 'sys_platform == "win32"' don't match your environment
Requirement already satisfied: certifi in /usr/local/lib/python3.10/dist-packages (from -r /home/gamebuster/Desktop/autosplit/AutoSplit/scripts/requirements.txt (line 13)) (2022.12.7)
Requirement already satisfied: ImageHash>=4.3.1 in /usr/local/lib/python3.10/dist-packages (from -r /home/gamebuster/Desktop/autosplit/AutoSplit/scripts/requirements.txt (line 14)) (4.3.1)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.10/dist-packages (from -r /home/gamebuster/Desktop/autosplit/AutoSplit/scripts/requirements.txt (line 16)) (1.24.3)
Requirement already satisfied: opencv-python-headless>=4.6 in /usr/local/lib/python3.10/dist-packages (from -r /home/gamebuster/Desktop/autosplit/AutoSplit/scripts/requirements.txt (line 17)) (4.7.0.72)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from -r /home/gamebuster/Desktop/autosplit/AutoSplit/scripts/requirements.txt (line 18)) (23.1)
Requirement already satisfied: Pillow>=9.2 in /usr/local/lib/python3.10/dist-packages (from -r /home/gamebuster/Desktop/autosplit/AutoSplit/scripts/requirements.txt (line 19)) (9.5.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.10/dist-packages (from -r /home/gamebuster/Desktop/autosplit/AutoSplit/scripts/requirements.txt (line 20)) (5.9.5)
Requirement already satisfied: PyAutoGUI in /usr/local/lib/python3.10/dist-packages (from -r /home/gamebuster/Desktop/autosplit/AutoSplit/scripts/requirements.txt (line 21)) (0.9.53)
Requirement already satisfied: PyQt6>=6.4.0 in /usr/local/lib/python3.10/dist-packages (from -r /home/gamebuster/Desktop/autosplit/AutoSplit/scripts/requirements.txt (line 24)) (6.5.0)
Requirement already satisfied: requests<=2.28.1 in /usr/local/lib/python3.10/dist-packages (from -r /home/gamebuster/Desktop/autosplit/AutoSplit/scripts/requirements.txt (line 25)) (2.28.1)
Requirement already satisfied: toml in /usr/local/lib/python3.10/dist-packages (from -r /home/gamebuster/Desktop/autosplit/AutoSplit/scripts/requirements.txt (line 26)) (0.10.2)
Requirement already satisfied: pyinstaller>=5.5 in /usr/local/lib/python3.10/dist-packages (from -r /home/gamebuster/Desktop/autosplit/AutoSplit/scripts/requirements.txt (line 29)) (5.10.1)
Requirement already satisfied: pyinstaller-hooks-contrib>=2022.9 in /usr/local/lib/python3.10/dist-packages (from -r /home/gamebuster/Desktop/autosplit/AutoSplit/scripts/requirements.txt (line 30)) (2023.2)
Requirement already satisfied: PySide6-Essentials>=6.4.0.1 in /usr/local/lib/python3.10/dist-packages (from -r /home/gamebuster/Desktop/autosplit/AutoSplit/scripts/requirements.txt (line 31)) (6.5.0)
Requirement already satisfied: bandit in /usr/local/lib/python3.10/dist-packages (from -r /home/gamebuster/Desktop/autosplit/AutoSplit/scripts/requirements-dev.txt (line 10)) (1.7.5)
Requirement already satisfied: flake8>=6 in /usr/local/lib/python3.10/dist-packages (from -r /home/gamebuster/Desktop/autosplit/AutoSplit/scripts/requirements-dev.txt (line 11)) (6.0.0)
Requirement already satisfied: flake8-builtins in /usr/local/lib/python3.10/dist-packages (from -r /home/gamebuster/Desktop/autosplit/AutoSplit/scripts/requirements-dev.txt (line 12)) (2.1.0)
Requirement already satisfied: flake8-bugbear in /usr/local/lib/python3.10/dist-packages (from -r /home/gamebuster/Desktop/autosplit/AutoSplit/scripts/requirements-dev.txt (line 13)) (23.3.23)
Requirement already satisfied: flake8-class-attributes-order in /usr/local/lib/python3.10/dist-packages (from -r /home/gamebuster/Desktop/autosplit/AutoSplit/scripts/requirements-dev.txt (line 14)) (0.1.3)
Requirement already satisfied: flake8-comprehensions>=3.8 in /usr/local/lib/python3.10/dist-packages (from -r /home/gamebuster/Desktop/autosplit/AutoSplit/scripts/requirements-dev.txt (line 15)) (3.12.0)
Requirement already satisfied: flake8-datetimez in /usr/local/lib/python3.10/dist-packages (from -r /home/gamebuster/Desktop/autosplit/AutoSplit/scripts/requirements-dev.txt (line 16)) (20.10.0)
Requirement already satisfied: flake8-noqa>=1.3.0 in /usr/local/lib/python3.10/dist-packages (from -r /home/gamebuster/Desktop/autosplit/AutoSplit/scripts/requirements-dev.txt (line 17)) (1.3.1)
Requirement already satisfied: flake8-pyi>=22.11.0 in /usr/local/lib/python3.10/dist-packages (from -r /home/gamebuster/Desktop/autosplit/AutoSplit/scripts/requirements-dev.txt (line 18)) (23.4.1)
Requirement already satisfied: flake8-simplify in /usr/local/lib/python3.10/dist-packages (from -r /home/gamebuster/Desktop/autosplit/AutoSplit/scripts/requirements-dev.txt (line 19)) (0.20.0)
Requirement already satisfied: pep8-naming in /usr/local/lib/python3.10/dist-packages (from -r /home/gamebuster/Desktop/autosplit/AutoSplit/scripts/requirements-dev.txt (line 20)) (0.13.3)
Requirement already satisfied: pylint<3.0.0,>=2.14 in /usr/local/lib/python3.10/dist-packages (from -r /home/gamebuster/Desktop/autosplit/AutoSplit/scripts/requirements-dev.txt (line 21)) (2.17.3)
Requirement already satisfied: add-trailing-comma>=2.3.0 in /usr/local/lib/python3.10/dist-packages (from -r /home/gamebuster/Desktop/autosplit/AutoSplit/scripts/requirements-dev.txt (line 23)) (2.4.0)
Requirement already satisfied: autopep8>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from -r /home/gamebuster/Desktop/autosplit/AutoSplit/scripts/requirements-dev.txt (line 24)) (2.0.2)
Requirement already satisfied: isort in /usr/local/lib/python3.10/dist-packages (from -r /home/gamebuster/Desktop/autosplit/AutoSplit/scripts/requirements-dev.txt (line 25)) (5.12.0)
Requirement already satisfied: unify in /usr/local/lib/python3.10/dist-packages (from -r /home/gamebuster/Desktop/autosplit/AutoSplit/scripts/requirements-dev.txt (line 26)) (0.5)
Requirement already satisfied: types-d3dshot in /usr/local/lib/python3.10/dist-packages (from -r /home/gamebuster/Desktop/autosplit/AutoSplit/scripts/requirements-dev.txt (line 32)) (0.1.0.5)
Requirement already satisfied: types-keyboard in /usr/local/lib/python3.10/dist-packages (from -r /home/gamebuster/Desktop/autosplit/AutoSplit/scripts/requirements-dev.txt (line 33)) (0.13.2.7)
Requirement already satisfied: types-Pillow in /usr/local/lib/python3.10/dist-packages (from -r /home/gamebuster/Desktop/autosplit/AutoSplit/scripts/requirements-dev.txt (line 34)) (9.5.0.1)
Requirement already satisfied: types-psutil in /usr/local/lib/python3.10/dist-packages (from -r /home/gamebuster/Desktop/autosplit/AutoSplit/scripts/requirements-dev.txt (line 35)) (5.9.5.12)
Requirement already satisfied: types-PyAutoGUI in /usr/local/lib/python3.10/dist-packages (from -r /home/gamebuster/Desktop/autosplit/AutoSplit/scripts/requirements-dev.txt (line 36)) (0.9.3.5)
Requirement already satisfied: types-pyinstaller in /usr/local/lib/python3.10/dist-packages (from -r /home/gamebuster/Desktop/autosplit/AutoSplit/scripts/requirements-dev.txt (line 37)) (5.10.0.0)
Requirement already satisfied: types-pywin32 in /usr/local/lib/python3.10/dist-packages (from -r /home/gamebuster/Desktop/autosplit/AutoSplit/scripts/requirements-dev.txt (line 38)) (306.0.0.1)
Requirement already satisfied: types-requests in /usr/local/lib/python3.10/dist-packages (from -r /home/gamebuster/Desktop/autosplit/AutoSplit/scripts/requirements-dev.txt (line 39)) (2.28.11.17)
Requirement already satisfied: types-toml in /usr/local/lib/python3.10/dist-packages (from -r /home/gamebuster/Desktop/autosplit/AutoSplit/scripts/requirements-dev.txt (line 40)) (0.10.8.6)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.10/dist-packages (from -r /home/gamebuster/Desktop/autosplit/AutoSplit/scripts/requirements-dev.txt (line 41)) (4.5.0)
Requirement already satisfied: PyWavelets in /usr/local/lib/python3.10/dist-packages (from ImageHash>=4.3.1->-r /home/gamebuster/Desktop/autosplit/AutoSplit/scripts/requirements.txt (line 14)) (1.4.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from ImageHash>=4.3.1->-r /home/gamebuster/Desktop/autosplit/AutoSplit/scripts/requirements.txt (line 14)) (1.10.0)
Requirement already satisfied: pymsgbox in /usr/local/lib/python3.10/dist-packages (from PyAutoGUI->-r /home/gamebuster/Desktop/autosplit/AutoSplit/scripts/requirements.txt (line 21)) (1.0.9)
Requirement already satisfied: PyTweening>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from PyAutoGUI->-r /home/gamebuster/Desktop/autosplit/AutoSplit/scripts/requirements.txt (line 21)) (1.0.4)
Requirement already satisfied: pyscreeze>=0.1.21 in /usr/local/lib/python3.10/dist-packages (from PyAutoGUI->-r /home/gamebuster/Desktop/autosplit/AutoSplit/scripts/requirements.txt (line 21)) (0.1.28)
Requirement already satisfied: pygetwindow>=0.0.5 in /usr/local/lib/python3.10/dist-packages (from PyAutoGUI->-r /home/gamebuster/Desktop/autosplit/AutoSplit/scripts/requirements.txt (line 21)) (0.0.9)
Requirement already satisfied: mouseinfo in /usr/local/lib/python3.10/dist-packages (from PyAutoGUI->-r /home/gamebuster/Desktop/autosplit/AutoSplit/scripts/requirements.txt (line 21)) (0.1.3)
Requirement already satisfied: python3-Xlib in /usr/local/lib/python3.10/dist-packages (from PyAutoGUI->-r /home/gamebuster/Desktop/autosplit/AutoSplit/scripts/requirements.txt (line 21)) (0.15)
Requirement already satisfied: PyQt6-sip<14,>=13.4 in /usr/local/lib/python3.10/dist-packages (from PyQt6>=6.4.0->-r /home/gamebuster/Desktop/autosplit/AutoSplit/scripts/requirements.txt (line 24)) (13.4.0)
Requirement already satisfied: PyQt6-Qt6>=6.5.0 in /usr/local/lib/python3.10/dist-packages (from PyQt6>=6.4.0->-r /home/gamebuster/Desktop/autosplit/AutoSplit/scripts/requirements.txt (line 24)) (6.5.0)
Requirement already satisfied: charset-normalizer<3,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<=2.28.1->-r /home/gamebuster/Desktop/autosplit/AutoSplit/scripts/requirements.txt (line 25)) (2.1.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3/dist-packages (from requests<=2.28.1->-r /home/gamebuster/Desktop/autosplit/AutoSplit/scripts/requirements.txt (line 25)) (3.3)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/lib/python3/dist-packages (from requests<=2.28.1->-r /home/gamebuster/Desktop/autosplit/AutoSplit/scripts/requirements.txt (line 25)) (1.26.5)
Requirement already satisfied: setuptools>=42.0.0 in /usr/local/lib/python3.10/dist-packages (from pyinstaller>=5.5->-r /home/gamebuster/Desktop/autosplit/AutoSplit/scripts/requirements.txt (line 29)) (67.7.2)
Requirement already satisfied: altgraph in /usr/local/lib/python3.10/dist-packages (from pyinstaller>=5.5->-r /home/gamebuster/Desktop/autosplit/AutoSplit/scripts/requirements.txt (line 29)) (0.17.3)
Requirement already satisfied: shiboken6==6.5.0 in /usr/local/lib/python3.10/dist-packages (from PySide6-Essentials>=6.4.0.1->-r /home/gamebuster/Desktop/autosplit/AutoSplit/scripts/requirements.txt (line 31)) (6.5.0)
Requirement already satisfied: GitPython>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from bandit->-r /home/gamebuster/Desktop/autosplit/AutoSplit/scripts/requirements-dev.txt (line 10)) (3.1.30)
Requirement already satisfied: PyYAML>=5.3.1 in /usr/lib/python3/dist-packages (from bandit->-r /home/gamebuster/Desktop/autosplit/AutoSplit/scripts/requirements-dev.txt (line 10)) (5.4.1)
Requirement already satisfied: stevedore>=1.20.0 in /usr/local/lib/python3.10/dist-packages (from bandit->-r /home/gamebuster/Desktop/autosplit/AutoSplit/scripts/requirements-dev.txt (line 10)) (4.1.1)
Requirement already satisfied: rich in /usr/local/lib/python3.10/dist-packages (from bandit->-r /home/gamebuster/Desktop/autosplit/AutoSplit/scripts/requirements-dev.txt (line 10)) (13.3.4)
Requirement already satisfied: mccabe<0.8.0,>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from flake8>=6->-r /home/gamebuster/Desktop/autosplit/AutoSplit/scripts/requirements-dev.txt (line 11)) (0.7.0)
Requirement already satisfied: pycodestyle<2.11.0,>=2.10.0 in /usr/local/lib/python3.10/dist-packages (from flake8>=6->-r /home/gamebuster/Desktop/autosplit/AutoSplit/scripts/requirements-dev.txt (line 11)) (2.10.0)
Requirement already satisfied: pyflakes<3.1.0,>=3.0.0 in /usr/local/lib/python3.10/dist-packages (from flake8>=6->-r /home/gamebuster/Desktop/autosplit/AutoSplit/scripts/requirements-dev.txt (line 11)) (3.0.1)
Requirement already satisfied: attrs>=19.2.0 in /usr/local/lib/python3.10/dist-packages (from flake8-bugbear->-r /home/gamebuster/Desktop/autosplit/AutoSplit/scripts/requirements-dev.txt (line 13)) (22.2.0)
Requirement already satisfied: astor>=0.1 in /usr/local/lib/python3.10/dist-packages (from flake8-simplify->-r /home/gamebuster/Desktop/autosplit/AutoSplit/scripts/requirements-dev.txt (line 19)) (0.8.1)
Requirement already satisfied: platformdirs>=2.2.0 in /usr/local/lib/python3.10/dist-packages (from pylint<3.0.0,>=2.14->-r /home/gamebuster/Desktop/autosplit/AutoSplit/scripts/requirements-dev.txt (line 21)) (2.6.2)
Requirement already satisfied: astroid<=2.17.0-dev0,>=2.15.4 in /usr/local/lib/python3.10/dist-packages (from pylint<3.0.0,>=2.14->-r /home/gamebuster/Desktop/autosplit/AutoSplit/scripts/requirements-dev.txt (line 21)) (2.15.4)
Requirement already satisfied: tomlkit>=0.10.1 in /usr/local/lib/python3.10/dist-packages (from pylint<3.0.0,>=2.14->-r /home/gamebuster/Desktop/autosplit/AutoSplit/scripts/requirements-dev.txt (line 21)) (0.11.6)
Requirement already satisfied: dill>=0.2 in /usr/local/lib/python3.10/dist-packages (from pylint<3.0.0,>=2.14->-r /home/gamebuster/Desktop/autosplit/AutoSplit/scripts/requirements-dev.txt (line 21)) (0.3.6)
Requirement already satisfied: tomli>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from pylint<3.0.0,>=2.14->-r /home/gamebuster/Desktop/autosplit/AutoSplit/scripts/requirements-dev.txt (line 21)) (2.0.1)
Requirement already satisfied: tokenize-rt>=3.0.1 in /usr/local/lib/python3.10/dist-packages (from add-trailing-comma>=2.3.0->-r /home/gamebuster/Desktop/autosplit/AutoSplit/scripts/requirements-dev.txt (line 23)) (5.0.0)
Requirement already satisfied: untokenize in /usr/local/lib/python3.10/dist-packages (from unify->-r /home/gamebuster/Desktop/autosplit/AutoSplit/scripts/requirements-dev.txt (line 26)) (0.1.1)
Requirement already satisfied: types-PyScreeze in /usr/local/lib/python3.10/dist-packages (from types-PyAutoGUI->-r /home/gamebuster/Desktop/autosplit/AutoSplit/scripts/requirements-dev.txt (line 36)) (0.1.0.7)
Requirement already satisfied: types-setuptools in /usr/local/lib/python3.10/dist-packages (from types-pyinstaller->-r /home/gamebuster/Desktop/autosplit/AutoSplit/scripts/requirements-dev.txt (line 37)) (67.7.0.0)
Requirement already satisfied: types-urllib3<1.27 in /usr/local/lib/python3.10/dist-packages (from types-requests->-r /home/gamebuster/Desktop/autosplit/AutoSplit/scripts/requirements-dev.txt (line 39)) (1.26.25.10)
Requirement already satisfied: lazy-object-proxy>=1.4.0 in /usr/local/lib/python3.10/dist-packages (from astroid<=2.17.0-dev0,>=2.15.4->pylint<3.0.0,>=2.14->-r /home/gamebuster/Desktop/autosplit/AutoSplit/scripts/requirements-dev.txt (line 21)) (1.8.0)
Requirement already satisfied: wrapt<2,>=1.11 in /usr/local/lib/python3.10/dist-packages (from astroid<=2.17.0-dev0,>=2.15.4->pylint<3.0.0,>=2.14->-r /home/gamebuster/Desktop/autosplit/AutoSplit/scripts/requirements-dev.txt (line 21)) (1.14.1)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.10/dist-packages (from GitPython>=1.0.1->bandit->-r /home/gamebuster/Desktop/autosplit/AutoSplit/scripts/requirements-dev.txt (line 10)) (4.0.10)
Requirement already satisfied: pyrect in /usr/local/lib/python3.10/dist-packages (from pygetwindow>=0.0.5->PyAutoGUI->-r /home/gamebuster/Desktop/autosplit/AutoSplit/scripts/requirements.txt (line 21)) (0.2.0)
Requirement already satisfied: pbr!=2.1.0,>=2.0.0 in /usr/lib/python3/dist-packages (from stevedore>=1.20.0->bandit->-r /home/gamebuster/Desktop/autosplit/AutoSplit/scripts/requirements-dev.txt (line 10)) (5.8.0)
Requirement already satisfied: pyperclip in /usr/local/lib/python3.10/dist-packages (from mouseinfo->PyAutoGUI->-r /home/gamebuster/Desktop/autosplit/AutoSplit/scripts/requirements.txt (line 21)) (1.8.2)
Requirement already satisfied: markdown-it-py<3.0.0,>=2.2.0 in /usr/local/lib/python3.10/dist-packages (from rich->bandit->-r /home/gamebuster/Desktop/autosplit/AutoSplit/scripts/requirements-dev.txt (line 10)) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from rich->bandit->-r /home/gamebuster/Desktop/autosplit/AutoSplit/scripts/requirements-dev.txt (line 10)) (2.15.1)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.10/dist-packages (from gitdb<5,>=4.0.1->GitPython>=1.0.1->bandit->-r /home/gamebuster/Desktop/autosplit/AutoSplit/scripts/requirements-dev.txt (line 10)) (5.0.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.10/dist-packages (from markdown-it-py<3.0.0,>=2.2.0->rich->bandit->-r /home/gamebuster/Desktop/autosplit/AutoSplit/scripts/requirements-dev.txt (line 10)) (0.1.2)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

changed 1 package, and audited 2 packages in 2s

found 0 vulnerabilities
Generated code from .ui files
Generated build number: "2304251358"
Set repository to "ool/AutoSplit"

```

I then tried to launch the program by calling `./scripts/start.ps1`, and get the no module named 'win32' error.

Am I missing a dependency?

**Comment by Avasam** [comment]
I'll refer you to https://github.com/Toufool/AutoSplit/issues/224 for progress on Linux support.
The ongoing branch can be found here: https://github.com/Toufool/AutoSplit/pull/153
